#!/usr/bin/with-contenv bash

# Create squeezeboxserver user and group
groupadd -g $S_GID squeezeboxserver
useradd -o -u $S_UID -g $S_GID -m -d $SQUEEZE_VOL -c 'Logitech Media Server' squeezeboxserver

# Check that squeezebox folders exist, then create them
for subdir in prefs logs cache playlist; do
    if [ -d "$SQUEEZE_VOL/$subdir" ];then
        echo "Le dossier $SQUEEZE_VOL/$subdir existe déjà";
    else
        echo "Le dossier $SQUEEZE_VOL/$subdir n'existe pas encore, création en cours"
        mkdir -p $SQUEEZE_VOL/$subdir
    fi
done

# Fix permissions
chown -R squeezeboxserver:squeezeboxserver $SQUEEZE_VOL
